### ISSUE TITLE
Add example usage for one controller

### ISSUE THREAD

**Issue by Rene36** [mamin27/ecomet_i2c_raspberry_tools#2]
To better understand the behavior an example would be very helpful.

**Comment by mamin27** [comment]
Some examples are in documentation. (see the links, the separate for python driver and pascal GUI) Also test scripts (python) are prepared for each chip. In the future I plan to prepare wiki part. Maybe some videos and description of testing at real hardware. Best way is to see example at hardware. Currently it is still prototypes. 
Some of it are finalized some needs re-designing. HDC1080, eeprom, pca9632 is almost done. EMC2301 board needs to be redesigning ... 
In my plans are another 10 sensor chips but would like to not open new development till old ones are not developed in driver and GUI part. These chips would be used in separate project internally and these code was for understanding how the sensors and i2c realy works. Future HW would be connected to the Pi at the cable from 30cm to 10m so it needs to be also prepared for such situation.

**Comment by mamin27** [comment]
I was added documentation to separate Markdown files for each Perl, Free Pascal code. If you have any question don't hesitate to send me feedback.
