### ISSUE TITLE
Generate fan_type.py

### ISSUE THREAD

**Issue by philippebourcier** [mamin27/ecomet_i2c_raspberry_tools#4]
Hi,

So I used your code for a Pi board called BitPiRat with an emc2302 on it :
https://github.com/philippebourcier/bitpirat_fanctrl
😎

It uses a 5V 4-Pin PWM fan headers, like most Pi CM4 boards and since a NF-A8 seems a bit overkill, I got myself a NF-A4x20.

Question is :

Do you think fan_type.py needs to be updated for the NF-A4x20 or will it work "as is" ?
The specs : https://noctua.at/en/nf-a4x20-pwm/specification

If so, how do I generate a new fan_type.py file ?
I can't see the relation about the specs on the NF-A8 page (ie: max RPM 2200) and the values on fan_type.py. 🤷‍♂️

Right now everything works, but still, I'm asking, just to be sure (and smarter, in the end). 😅

**Comment by mamin27** [comment]
Hi Philippe,

I will be very glad when we will cooperate at this issue together. I have not emc2302 chip but You could upgrade code and to be contributor of my project for emc2302 modification (there is 2 FAN managed) 
I suppose everything could be tailored also for new fan type. There is also GUI program where you could test different parameters for fan to tailor them to the real fan parameter. I used GUI for identification of fan_type parameters. 
I don't know If GUI will work also with emc2302 chip. I could modify it but I need your help also for testing.

One note. When you write your own project that is nice but there should be also mentioned link to the origin project.

Regards

Marian

**Comment by mamin27** [comment]
I added the note into **Requestor Interests**: add EMC2302-05 chips in design in my long term plan. It supposed that you will not answer.
