### ISSUE TITLE
Problem Reading RPM from EMC2301

### ISSUE THREAD

**Issue by n384sm** [mamin27/ecomet_i2c_raspberry_tools#6]
Hi,

I have been trying to get an EMC2301 to work with a Noctua NF-8A PWM Fan ([fan specs](https://noctua.at/en/nf-a8-pwm/specification)).

Using a Raspberry PI over i2c, I can control the speed the fan using the EMC2301 using the following two commands:

i2cset -y 1 0x2f 0x30 0xff
i2cset -y 1 0x2f 0x30 0x00

However, I am unable to reliably read the fan RPM. I have used the open source test script ([Test Script](https://github.com/mamin27/ecomet_i2c_raspberry_tools/blob/master/python_test_scripts/emc2301/emc2301_i2c_test.py)) and pasted its output below.

As you can see below, the RPM values being printed are not sane. I am assuming its a configuration issue and would love guidance to that effect. Thank you so much.

Regards,
S.

pi@raspberrypi:~/fan/emc2301 $ sudo python3 emc2301_i2c_test.py
3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
ecomet.emc2301: INFO   Start logging ...
:TEST_PASSED:
ecomet.emc2301: INFO   PRODUCT Read correct
ecomet.emc2301: INFO   PRODUCT ID: 37
ecomet.emc2301: INFO   MANUFACTURER Read correct
ecomet.emc2301: INFO   MANUF ID: 5D
ecomet.emc2301: INFO   REVISION Read correct
ecomet.emc2301: INFO   REVISION ID: 80

{'CONF': {'MASK': 'UNMASKED', 'DIS_TO': 'DISABLED', 'WD_EN': 'DISABLED', 'DR_EXT_CLK': 'CLK_INPUT', 'USE_EXT_CLK': 'INTERNAL', 'EN_ALGO': 'DISABLED', 'RANGE': '500>1', 'EDGES': '5>2POLE>1', 'UPDATE': '100ms', 'EN_RRC': 'ENABLED', 'GLITCH_EN': 'DISABLED', 'DER_OPT': 'BASIC_DERIVATE', 'ERR_RNG': '0RPM', 'GAIND': '4x', 'GAINI': '4x', 'GAINP': '4x'}, 'FAN_STAT': {'WATCH': 'NOT_SET', 'DRIVE_FAIL': 'REACH', 'FAN_SPIN': 'SPIN', 'FAN_STALL': 'STALL', 'FAN_INT': 'NO_ALERT', 'FAN_SETTING': 0.0}, 'SPIN': {'FAN_SPIN_UP_DRIVE_FAIL_CNT': 'DISABLE', 'FAN_SPIN_UP_NOKICK': 'SPIN', 'FAN_SPIN_UP_LVL': '60%', 'FAN_SPIN_UP_TIME': '500ms', 'FAN_MAX_STEP': 16, 'FAN_MIN_DRIVE': 40.0}, 'PWM': {'PWM_POLARITY': 'NORMAL', 'PWM_OUTPUT': 'OPEN-DRAIN', 'PWM_BASE': '26.00kHz', 'PWM_DIVIDE': 1}, 'TACH': {'TACH_COUNT': 7840, 'FAN_FAIL_BAND': 0, 'TACH_TARGET': 8191, 'TACH_READ': 5647}, 'ID': {'PRODUCT_ID': '37', 'MANUF_ID': '5D', 'REVISION_ID': '80'}, 'LOCK': 'UNLOCKED'}
---------------------------------

********* Changing Speed To: 0 **********

computing speed
res: 4022
poles: 2
edges: 5
mul: 1
tach: 32768
output: 977
977 RPM

computing speed
res: 6890
poles: 2
edges: 5
mul: 1
tach: 32768
output: 570
570 RPM

computing speed
res: 3949
poles: 2
edges: 5
mul: 1
tach: 32768
output: 995
995 RPM

computing speed
res: 3981
poles: 2
edges: 5
mul: 1
tach: 32768
output: 987
987 RPM

computing speed
res: 3962
poles: 2
edges: 5
mul: 1
tach: 32768
output: 992
992 RPM

********* Changing Speed To: 50 **********

computing speed
res: 3804
poles: 2
edges: 5
mul: 1
tach: 32768
output: 1033
1033 RPM

computing speed
res: 9
poles: 2
edges: 5
mul: 1
tach: 32768
output: 436906
436906 RPM

computing speed
res: 14
poles: 2
edges: 5
mul: 1
tach: 32768
output: 280868
280868 RPM

computing speed
res: 9
poles: 2
edges: 5
mul: 1
tach: 32768
output: 436906
436906 RPM

computing speed
res: 9
poles: 2
edges: 5
mul: 1
tach: 32768
output: 436906
436906 RPM

********* Changing Speed To: 100 **********

computing speed
res: 9
poles: 2
edges: 5
mul: 1
tach: 32768
output: 436906
436906 RPM

computing speed
res: 4
poles: 2
edges: 5
mul: 1
tach: 32768
output: 983040
983040 RPM

computing speed
res: 4
poles: 2
edges: 5
mul: 1
tach: 32768
output: 983040
983040 RPM

computing speed
res: 4
poles: 2
edges: 5
mul: 1
tach: 32768
output: 983040
983040 RPM

computing speed
res: 7
poles: 2
edges: 5
mul: 1
tach: 32768
output: 561737
561737 RPM

********* Changing Speed To: 160 **********

computing speed
res: 4
poles: 2
edges: 5
mul: 1
tach: 32768
output: 983040
983040 RPM

computing speed
res: 4
poles: 2
edges: 5
mul: 1
tach: 32768
output: 983040
983040 RPM

computing speed
res: 4
poles: 2
edges: 5
mul: 1
tach: 32768
output: 983040
983040 RPM

computing speed
res: 4
poles: 2
edges: 5
mul: 1
tach: 32768
output: 983040
983040 RPM

computing speed
res: 4
poles: 2
edges: 5
mul: 1
tach: 32768
output: 983040
983040 RPM
Speed: 200

computing speed
res: 4
poles: 2
edges: 5
mul: 1
tach: 32768
output: 983040
983040 RPM

computing speed
res: 4
poles: 2
edges: 5
mul: 1
tach: 32768
output: 983040
983040 RPM

********* Changing Speed To: 255 **********

computing speed
res: 8191
poles: 2
edges: 5
mul: 1
tach: 32768
output: 480
480 RPM

computing speed
res: 2658
poles: 2
edges: 5
mul: 1
tach: 32768
output: 1479
1479 RPM

computing speed
res: 8191
poles: 2
edges: 5
mul: 1
tach: 32768
output: 480
480 RPM

computing speed
res: 8191
poles: 2
edges: 5
mul: 1
tach: 32768
output: 480
480 RPM

computing speed
res: 6217
poles: 2
edges: 5
mul: 1
tach: 32768
output: 632
632 RPM

---------------------------------

**Comment by mamin27** [comment]
Hello,

Your problem would be probably reading speed RPM at TACH signal. I had same problem in the past and I made several schematic improvements. So I need info how you manage TACH signal (send me your schematic). Other issue is interference problem at your PCB.

Here is information of my test PCB board for managing FAN (12V or 24V) managed by I2C interface (long or short).
[wiki](https://github.com/mamin27/ecomet_i2c_raspberry_tools/wiki/_fan_board). Supporting me by [coffee](https://www.buymeacoffee.com/scQ8LwgTBt) #ecclima you can order it.

Parameters of fan (you are using same as me) you are able toset here:

![image](https://github.com/mamin27/ecomet_i2c_raspberry_tools/assets/26118162/1f73dff8-8001-45c8-99ea-fc4c3ce24452)
![image](https://github.com/mamin27/ecomet_i2c_raspberry_tools/assets/26118162/c58d3ade-f75c-42c7-adf6-e4c4898a0bf8)

There is not necessary to set them by i2cset command. The fan parameters are initialized by initialization of class

```python
sens = emc2301.EMC2301()
```
![image](https://github.com/mamin27/ecomet_i2c_raspberry_tools/assets/26118162/d64948ff-298d-4814-9f50-cf8f35a03e3e)

If you want to play with FAN & emc2301 parameters just thy to us GUI application.

[GUI](https://github.com/mamin27/ecomet_i2c_raspberry_tools/tree/master/bin) ... emc2301. The GUI tool working online. It is compatible with RPi3 & PRi4. (I am experimenting also with AllWinner CPU H616)

Note: for running python test script you would not necessary use sudo. It should work at common user. [RPi forum](https://forums.raspberrypi.com/viewtopic.php?t=58787)

Regards
MM

**Comment by mamin27** [comment]
Hi,

Yoy have problem 

If you want to play with FAN & emc2301 parameters just try to use GUI application.
Hello,

Your problem would be probably reading speed RPM at TACH signal. I had same problem in the past and I made several schematic improvements. So I need info how you manage TACH signal (send me your schematic). Other issue is interference problem at your PCB.

Here is information of my test PCB board for managing FAN (12V or 24V) managed by I2C interface (long or short).
wiki. Supporting me by coffee #ecclima you can order it.

Parameters of fan (you are using same as me) you are able toset here:

GUI ... emc2301. The GUI tool working online. It is compatible with RPi3 & PRi4. (I am experimenting also with AllWinner CPU H616)

Note: for running python test script you would not necessary use sudo. It should work at common user. [RPi forum](https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github)

**Comment by n384sm** [comment]
Thanks for writing. I have managed to improve the situation a little, but not completely. Now I can read RPM accurately from 0 to 100 PWM. Above 100 PWM up to and including 255 PWM, my RPM becomes zero. My schematic is attached. A3 is the EMC2301 chip. R13, R26, and R12 are pull-ups of 4.7 kOhms each.

<img width="494" alt="Screenshot 2023-06-09 at 2 10 45 AM" src="https://github.com/mamin27/ecomet_i2c_raspberry_tools/assets/45501841/f55fd211-b3ba-4eb0-86af-48acef076caa">

**Comment by mamin27** [comment]
You are not able to connect directly TACH signal from FAN to emc2301. Also PWM signal is wrongly connected. So you need to change it. Excuse me I am not able to recommend you correct schematics. It is my know-how. 

When you fix it, my code will help you. I will be glad if you support me when you give me a star at my project or you can order my test PCB board.

Regards

Marian

**Comment by n384sm** [comment]
Ok. Thanks.
